### your site title here

title: Wassery Blog

permalink: /:title

baseurl: 

sass: 
  style: compressed

### exclude the instructions / write-up in the README.md
exclude:
- README.md

plugins: ['jekyll-paginate']

# Pages
paginate: 5
paginate_path: "page:num"
